CREATE TABLE IF NOT EXISTS USER_INFO (
    USER_ID bigint NOT NULL AUTO_INCREMENT,
    USER_NAME varchar(100) NOT NULL,
    USER_KEY varchar(100) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID)
);